services:
  backend:
    build: .
    ports:
      - 8081:8081
    env_file:
      - .env

  postgres:
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
